services:

  postgres:
    image: postgres:latest
    env_file:
      - .env
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_ROOT}:/var/lib/postgresql/data
      - ${LOG_FOLDER_ROOT}/postgres:/var/log/postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  nginx:
    image: nginx:latest
    ports:
      - "8011:80"
    depends_on:
      - app
    restart: always
    volumes:
      - ./static:/var/www/html/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${LOG_FOLDER_ROOT}/nginx:/var/log/nginx

  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    image: "monitoring"
    restart: always
    command: gunicorn frx.wsgi
    entrypoint: /home/code/entrypoint.sh
    volumes:
      - ./static:/home/code/static
      - ${LOG_FOLDER_ROOT}:/home/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  celery:
    image: "monitoring"
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    restart: always
    hostname: celery
    entrypoint: celery
    command: -A frx worker -B -E -l INFO -s /home/celery-beat-schedule
    volumes:
      - ${LOG_FOLDER_ROOT}:/home/logs
    depends_on:
      - app
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:latest
